[package]
name = "ferrodb"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
lazy_static = "1.4"
lru = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.2"
